"""Update pass_secure

Revision ID: 261730bc3ad8
Revises: 833b770dde59
Create Date: 2022-02-02 12:55:44.057031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261730bc3ad8'
down_revision = '833b770dde59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
